primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#929191 '

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
textColor = '#FFFFFF'

